whatis("Set up environment for Python 3.6.5")
local home = os.getenv("HOME")
local version = myModuleVersion()
local pkgName = myModuleName()
local pkg = pathJoin(home,"user_programs","pkg",pkgName,version,"bin")
load("cuda")
prereq_any("cuda")
prepend_path("PATH", pkg)
setenv("PYTHONPATH","/nas/longleaf/home/sdgeorge/user_programs/pkg/Python/3.6.5/lib/python3.6:/nas/longleaf/home/sdgeorge/user_programs/pkg/Python/3.6.5/lib/python3.6/site-packages")
prepend_path("LD_LIBRARY_PATH","/nas/longleaf/home/sdgeorge/user_programs/pkg/Python/3.6.5/lib:/nas/longleaf/apps/r/3.2.3/lib64/R/lib")
setenv("THEANO_FLAGS","cuda.root=/usr/local/cuda,device=gpu,floatX=float32,blas.ldflags=-lblas -ltatlas -llapack -lgfortran")